name: Setup cargo

description: Install Rust toolchain and use cargo cache to speed up compilation time

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@v2

    - name: Install toolchain
      shell: bash
      run: rustup toolchain install 1.70 --profile minimal
